### ISSUE TITLE
Line number is too high

### ISSUE THREAD

**Issue by SkytAsul** [MrMicky-FR/FastBoard#17]
I can't understand those lines: https://github.com/MrMicky-FR/FastBoard/blob/37f3f85e37cc8506ea8fed2e61903bacdd031d75/src/main/java/fr/mrmicky/fastboard/FastBoard.java#L439-L441

What are there meant for?
Why do the error message contains `this.lines.size()` instead of `line`?

**Comment by xIsm4** [comment]
Just checks if the line number it's too high and trows exceptions nothing more.

**Comment by SkytAsul** [comment]
Too high for what?
I'm getting exception when updating my scoreboard with some 20 lines. I don't understand what do "COLOR_CODES" have to do with this.

**Comment by MrMicky-FR** [comment]
> Why do the error message contains this.lines.size() instead of line?
It’s an typo in the code, I will fix this in the next update as it’s a small issue

> Too high for what? I'm getting exception when updating my scoreboard with some 20 lines.
The vanilla Minecraft client can only display up to 15 scoreboard lines

> I don't understand what do "COLOR_CODES" have to do with this.
Because each scoreboard line use a different color for team name, it would be possible to add support for more lines by using multiple color codes, but it wouldn’t be very useful as the client only displays 15 lines

**Comment by SkytAsul** [comment]
I think it would be better to normalize this:
- either you throw an error when the passed "lines" list contains more than 15 elements
- either you don't throw any error and don't handle elements after the 15th one
Throwing an error when the lines size contains more than 22 elements is unintuitive and confusive.
