### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by Splitrox** [MrMicky-FR/FastBoard#63]
Hi Micky, I'm not really sure if this is a performance issue that can be improved or if it is a bottleneck situation, in any case I'm going to share with you what i got from sparks:
![image](https://github.com/user-attachments/assets/8c88fbb7-5cee-44ad-8c6b-e0fdb1379127)

**Comment by MrMicky-FR** [comment]
Most of the time usage comes from CraftBukkit, over which we don’t have any control. As some ways to reduce the impact of FastBoard, you could try to only update the lines when needed (by using an event-driven approach rather than just a repeating task) and/or update the lines asynchronously, as FastBoard is 100% packed based. 

An interesting approach would be to try with Adventure version of FastBoard, as the serialization implementation is different, to compare if it improves the performances
